### ISSUE TITLE
export built in whenever available?

### ISSUE THREAD

**Issue by jimmywarting** [jsdom/domexception#14]
NodeJS have DOMexception built in now and globally available as of v17+. just wondering if you maybe could export the built in whenever it's available and fallback to your code with conditionall require

otherwise there is an inconsistency if someone where to do `instanceof` checks

**Comment by domenic** [comment]
Nope, Node's implementations don't work with the jsdom constructs.

**Comment by jimmywarting** [comment]
> don't work with the jsdom constructs

a bit confused... care to explain more? I'm only curious. just want to know why
